# Import libraries and dataframes

In [1]:
# import library
import numpy as np
import pandas as pd
import os
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path = r'G:\Career Foundery\CFundry-6'
elect_prod = pd.read_pickle(os.path.join(path, '2 Data set', 'Modified', 'elect_production.pkl'))
elect_prod.head()

   country time-period                    fuel-type  value(GWH)
0  Albania     2018-01  Coal and manufactured gases         0.0
1  Albania     2018-02  Coal and manufactured gases         0.0
2  Albania     2018-03  Coal and manufactured gases         0.0
3  Albania     2018-04  Coal and manufactured gases         0.0
4  Albania     2018-05  Coal and manufactured gases         0.0

In [3]:
set(elect_prod['fuel-type'])

{'Coal and manufactured gases',
 'Combustible fuels',
 'Combustible fuels - non-renewable',
 'Combustible fuels - renewable',
 'Geothermal',
 'Hydro',
 'Mixed hydro power',
 'Natural gas',
 'Nuclear fuels and other fuels n.e.c.',
 'Oil and petroleum products (excluding biofuel portion)',
 'Other fuels n.e.c.',
 'Other renewable energies',
 'Pumped hydro power',
 'Pure hydro power',
 'Solar',
 'Solar photovoltaic',
 'Solar thermal',
 'Total',
 'Wind',
 'Wind off shore',
 'Wind on shore'}

In [12]:
req = ['Coal and manufactured gases', 'Combustible fuels', 'Geothermal', 'Hydro', 'Natural gas', 'Nuclear fuels and other fuels n.e.c.',
      'Oil and petroleum products (excluding biofuel portion)', 'Solar', 'Wind']

In [4]:
elect_prod.groupby('fuel-type')['value(GWH)'].sum()

fuel-type
Coal and manufactured gases                               3.158635e+06
Combustible fuels                                         1.006673e+07
Combustible fuels - non-renewable                         2.048446e+05
Combustible fuels - renewable                             6.287146e+05
Geothermal                                                1.153150e+05
Hydro                                                     3.892191e+06
Mixed hydro power                                         1.579531e+05
Natural gas                                               3.006655e+06
Nuclear fuels and other fuels n.e.c.                      5.177883e+06
Oil and petroleum products (excluding biofuel portion)    1.911114e+05
Other fuels n.e.c.                                        4.578109e+04
Other renewable energies                                  5.824960e+02
Pumped hydro power                                        1.077085e+05
Pure hydro power                                          2.942567e+06
Solar                                                     8.220529e+05
Solar photovoltaic                                        7.900842e+05
Solar thermal                                             2.636630e+04
Total                                                     2.295884e+07
Wind                                                      2.726483e+06
Wind off shore                                            3.309493e+05
Wind on shore                                             1.731200e+06
Name: value(GWH), dtype: float64

In [13]:
new = elect_prod[elect_prod['fuel-type'].isin(req)]
new

              country time-period                    fuel-type  value(GWH)
0             Albania     2018-01  Coal and manufactured gases       0.000
1             Albania     2018-02  Coal and manufactured gases       0.000
2             Albania     2018-03  Coal and manufactured gases       0.000
3             Albania     2018-04  Coal and manufactured gases       0.000
4             Albania     2018-05  Coal and manufactured gases       0.000
...               ...         ...                          ...         ...
39946  United Kingdom     2020-06                        Solar    1701.201
39947  United Kingdom     2020-07                        Solar    1495.099
39948  United Kingdom     2020-08                        Solar    1362.223
39949  United Kingdom     2020-09                        Solar    1273.614
39950  United Kingdom     2020-10                        Solar     653.311

[23405 rows x 4 columns]

In [14]:
set(new['fuel-type'])

{'Coal and manufactured gases',
 'Combustible fuels',
 'Geothermal',
 'Hydro',
 'Natural gas',
 'Nuclear fuels and other fuels n.e.c.',
 'Oil and petroleum products (excluding biofuel portion)',
 'Solar',
 'Wind'}

In [15]:
# save the new data frame
new.to_pickle(os.path.join(path, '2 Data set', 'Modified', 'elect_production2.pkl'))
new.to_csv(os.path.join(path, '2 Data set', 'Modified', 'elect_production2.csv'))

In [17]:
elect_prod[(elect_prod['country']=='Germany') & (elect_prod['time-period']=='2022-05')]

,country,time-period,fuel-type,value(GWH)
496,Germany,2022-05,Coal and manufactured gases,11876.289
2910,Germany,2022-05,Combustible fuels,20308.112
5634,Germany,2022-05,Combustible fuels - non-renewable,1422.378
7917,Germany,2022-05,Combustible fuels - renewable,1479.018
10258,Germany,2022-05,Natural gas,5180.808
12672,Germany,2022-05,Nuclear fuels and other fuels n.e.c.,2236.430
15396,Germany,2022-05,Oil and petroleum products (excluding biofuel ...,349.620
17809,Germany,2022-05,Hydro,1824.455
20533,Germany,2022-05,Pure hydro power,1387.650
22933,Germany,2022-05,Mixed hydro power,51.210
25333,Germany,2022-05,Pumped hydro power,385.595
27805,Germany,2022-05,Geothermal,23.000
30601,Germany,2022-05,Wind,7986.000
33325,Germany,2022-05,Wind on shore,6485.000
35686,Germany,2022-05,Wind off shore,1501.000
38047,Germany,2022-05,Solar,8159.000
40447,Germany,2022-05,Solar thermal,0.000
42847,Germany,2022-05,Solar photovoltaic,8159.000
45247,Germany,2022-05,Other renewable energies,0.000
47719,Germany,2022-05,Total,40565.630
50443,Germany,2022-05,Other fuels n.e.c.,28.633

In [19]:
20308.112 + 2236.430 +  1824.455 + 23.000 + 7986.000 + 8159.000 + 28.633

40565.630000000005